### ISSUE TITLE
GUI for stepping

### ISSUE THREAD

**Issue by petergjoel** [DEIS-Tools/DistributedExercisesAAU#22]
Make a GUI overlay in tkinter that displays the current state of the simulator and allows for interaction with the simulator via #21

**Comment by Mast3rwaf1z** [comment]
I am still waiting on the pull request at https://github.com/DEIS-Tools/DistributedExercisesAAU/pull/27 to finish the implementation of issue https://github.com/DEIS-Tools/DistributedExercisesAAU/issues/25
